sequenceDiagram
  participant participant_hasBalancedParentheses as hasBalancedParentheses
  participant participant_isPhone as isPhone
  participant_isPhone->>participant_hasBalancedParentheses: hasBalancedParentheses()
  participant_hasBalancedParentheses-->>participant_isPhone: return
